# Namų darbai 6. Numpy

In [33]:
# 1. Sukurkite tokį ndarray ir išsaugokite kintamąjame arr:
# [[5 4 3]
#  [3 2 1]
#  [1 0 6]
#  [6 5 4]]


import numpy as np

arr = np.array([
    [5,4,3],
    [3,2,1],
    [1,0,6],
    [6,5,4]
]
)

print(arr)


[[5 4 3]
 [3 2 1]
 [1 0 6]
 [6 5 4]]


In [4]:
# 2. Kiek dimensijų turi arr? Kokios jos?
# arr = [[5 4 3]
#        [3 2 1]
#        [1 0 6]
#        [6 5 4]]

numpy.ndarray

In [34]:
arr.shape

(4, 3)

In [ ]:
# 3. Atspausdinkite 3-ios eilutės antrąjį narį
# arr = [[5 4 3]
#        [3 2 1]
#        [1 0 6]
#        [6 5 4]]

In [35]:
arr[2,1] # pirmas eilute, antras stulpelis

0

In [ ]:
# 4. Atspausdinkite 2-os eilutės pirmą ir antrą narius
# arr = [[5 4 3]
#        [3 2 1]
#        [1 0 6]
#        [6 5 4]]

In [36]:
arr[1,:2]

array([3, 2])

In [ ]:
# 5. Atspausdinkite 3-ios ir 4 eilučių antrą ir trečią narius (t.y. iš viso 4 skaičius iš dešiniojo apatinio kampo)
# arr = [[5 4 3]
#        [3 2 1]
#        [1 0 6]
#        [6 5 4]]

In [37]:
arr[2:,1:]

array([[0, 6],
       [5, 4]])

In [ ]:
#6. Naudodami reshape() metodą pakeiskite arr taip, kad jo dimensijos būtų (6, 2)
# arr = [[5, 4, 3],
#        [3, 2, 1],
#        [1, 0, 6],
#        [6, 5, 4]]


In [38]:
arr = arr.reshape(6,2)
print(arr)

[[5 4]
 [3 3]
 [2 1]
 [1 0]
 [6 6]
 [5 4]]


In [ ]:
# 7. Transponuokite arr (po transponavimo shape turi būti (2, 6))
# arr = [[5, 4, 3],
#        [3, 2, 1],
#        [1, 0, 6],
#        [6, 5, 4]]

In [39]:
arr = arr.T
print(arr)
arr.shape

[[5 3 2 1 6 5]
 [4 3 1 0 6 4]]


(2, 6)

In [ ]:
# 8. Padauginkite visus šio array skaičius iš 8 ir atimkite iš visų 30, išsaugokite rezultatą kintamąjame arr_2
# arr = [[5 3 2 1 6 5]
#        [4 3 1 0 6 4]]


In [40]:
arr_2 = arr * 8 - 30
print(arr_2)

[[ 10  -6 -14 -22  18  10]
 [  2  -6 -22 -30  18   2]]


In [ ]:
# 9. Priskirkite visus neigiamus arr_2 narius kintamąjam arr_2_neg
# arr_2 = [[ 10  -6 -14 -22  18  10]
#        [  2  -6 -22 -30  18   2]]

In [43]:
arr_2_neg = arr_2[arr_2 < 0]
print(arr_2_neg)

[ -6 -14 -22  -6 -22 -30]


In [ ]:
# 10. Atspausdinkite arr_2_neg narių sumą ir sandaugą
# arr_2_neg = [ -6 -14 -22  -6 -22 -30]

In [52]:
print(f'suma: {arr_2_neg.sum()}')
print(f'saundauga: {arr_2_neg.prod()}')

suma: -100
saundauga: 7318080


In [ ]:
# 11. Atspausdinkite arr_2_neg medianą
# arr_2_neg = [ -6 -14 -22  -6 -22 -30]  -30 -22 -22 -14 -6 -6

In [55]:
print(f'mediana: {np.median(arr_2_neg)}')

mediana: -18.0
