# Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\vytau\AppData\Local\Programs\Python\Python38-32\python.exe -m pip install --upgrade pip' command.


In [3]:
a_list = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

print( a_list[1][1] )

6


In [2]:
import numpy as np

In [5]:
a_np = np.array( [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]   
)

print(a_np)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print( a_np[:, 1] )
print( a_np[1, 1] ) # row index, column index
print( a_np[:2, 1] )
print( a_np[:2, 1:3] )

[ 2  6 10]
6
[2 6]
[[2 3]
 [6 7]]


In [14]:
a_np.shape

(3, 4)

In [15]:
array_1d = np.array( [1, 5, 7, 9, 10, 15, 18] )

print(array_1d.shape)

(7,)
